config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pointing_sessions#index"
  resources :pointing_sessions do
    resources :participants, only: [ :index, :create ]
  end

  resources :participants do
    member do
      post :vote
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :pointing_session

  after_create_commit :refresh_participants
  after_update_commit :update_participant

  def display_vote
    if vote.blank?
      "None"
    elsif pointing_session.voting_complete?
      self.vote
    else
      "Voted"
    end
  end

  private

  def update_participant
    broadcast_update_to(self.pointing_session, target: self, partial: "participants/participant", locals: { participant: self })
    if self.pointing_session.voting_complete?
      refresh_participants
    end
    broadcast_update_to(
      self.pointing_session,
      target: "participant_#{self.id}_vote",
      partial: "participants/vote_form",
      locals: { participant: self, pointing_session: self.pointing_session }
    )
  end

  def refresh_participants
    broadcast_update_to(self.pointing_session, target: "participants", partial: "participants/list", locals: { pointing_session: self.pointing_session })
  end
end

app/models/pointing_session.rb
class PointingSession < ApplicationRecord
  has_many :participants,  dependent: :destroy
  after_update_commit :update_topic

  scope :stale, -> { where("updated_at <= ?", DateTime.now - 30.minutes) }

  module Constants
    Status = [
      WAITING = "WAITING",
      COMPLETED = "COMPLETED",
      VOTING = "VOTING"
    ].freeze
  end

  def refresh_topic(topic:)
    participants.each { |p| p.update!(vote: nil) }
    self.update!(topic:)
  end

  def status
    if self.topic.nil?
      Constants::Status::WAITING
    elsif self.participants.count  { |p| p.vote.nil? }
      Constants::Status::COMPLETED
    else
      Constants::Status::VOTING
    end
  end

  def voting_complete?
    participants.where(vote: nil).empty?
  end

  def stale?
    updated_at <= DateTime.now - 1.hour
  end

  private

  def update_topic
    broadcast_update_to(self, target: self, html: "<h3> Topic: #{self.topic} </h3>")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  def vote
    @participant = Participant.find(params[:id])
    @participant.update!(vote: vote_params[:vote])
  end

  def update
    @participant = Participant.find(params[:id])
    @participant.update!(update_participant_params)
  end


  private

  def vote_params
    params.expect(participant: [ :vote ])
  end

  def update_participant_params
    params.expect(participant: [ :name ])
  end
end

app/controllers/pointing_sessions_controller.rb
class PointingSessionsController < ApplicationController
  def index
    @pointing_sessions = PointingSession.all.order(created_at: :desc)
    @pointing_session = PointingSession.new(name: Faker::Movie.title)
  end

  def create
    @pointing_session = PointingSession.create(new_pointing_session_params)
    if !@pointing_session.valid?
      puts "Erros: #{@point_session.errors}"
      flash[:error] = "Invalid name"
      redirect_to :index
    else
      flash[:notice] = "Created new pointing session"
      redirect_to pointing_session_url(@pointing_session)
    end
  end

  def update
    @pointing_session = PointingSession.find(params[:id])
    @pointing_session.update!(update_pointing_session_params)
    @pointing_session.participants.each { |participant| participant.update!(vote: nil) }
  end

  def show
    @pointing_session = PointingSession.find(params[:id])
    if session[:participant_id]
      @participant = Participant.find_by(id: session[:participant_id])
    end

    if !@participant || @participant.pointing_session != @pointing_session
      @participant = @pointing_session.participants.create(name: Faker::FunnyName.name, administrator: @pointing_session.participants.empty?)
      session[:participant_id] = @participant.id
      flash[:message] = "Welcome #{@participant.name}"
    end
  end

  private

  def new_pointing_session_params
    params.expect(pointing_session: [ :name ])
  end

  def update_pointing_session_params
    params.expect(pointing_session: [ :topic ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pointing_sessions_helper.rb
module PointingSessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Pointsetta" %></title>
    <meta name="turbo-prefetch" content="false">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="stylesheet" href="https://fonts.xz.style/serve/inter.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@exampledev/new.css@1.1.2/new.min.css">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <div class="tagline">
        Pointsetta! Point flowers not fingers.
      </div>

      <%= yield %>

      <%= image_tag source="pointsetta.svg" %>
  </body>
</html>

app/views/participants/_form.html.erb
<div id='<%= "#{dom_id(participant)}_form" %>' >
  <%= form_with model: [participant]  do |form| %>
    <%= form.label "Your alias" %>
    <%= form.search_field(:name, class: 'create_input') %>
    <%= form.submit("Update") %>
  <% end %>
</div>

app/views/participants/_list.html.erb
<div id="participants" class="list">
  <h3>Participants:</h3>
  <table>
    <% pointing_session.participants.each do |participant| %>
      <tr id='<%= dom_id(participant) %>'>
        <%= render participant %>
      </tr>
    <% end %>
  </table>
</div>

app/views/participants/_participant.html.erb
<td>
  <%= participant.name %>
</td>
<td>
  <%= participant.display_vote %>
</td>

app/views/participants/_vote_form.html.erb
<div id='<%= "#{dom_id(participant)}_vote" %>'>
  <% if pointing_session.topic.present? %>
    <% if participant.vote.blank? %>
      <%= "Vote as #{participant.name}" %>
      <%=  form_with model: participant, url: vote_participant_path(participant), method: :post do |form| %>
        <%= form.search_field(:vote, class: 'create_input') %>
        <%= form.submit("Vote") %>
      <% end %>
    <% end %>
  <% else %>
    <%= render partial: '/participants/form', locals: { participant: participant, pointing_session: pointing_session } %>
  <% end %>
</div>

app/views/participants/_vote_form_turbostream.html.erb
<div id="<%= dom_id(@pointing_session)_votes %>">
  <% if @pointing_session.topic.present? && !@participant.vote.blank? %>
    <%= render :partial, 'vote_form' %>
  <% end %>
</div>

app/views/participants/list.html.erb
render partial :list

app/views/participants/show.html.erb
<%= link_to "Pointsetta Root", "/" %>
<h1>
  Pointing Session: <%= @pointing_session.name %>
</h1>

<h2>
  Welcome Participant! <%= @participant.name %>
</h2>

<%= "Current Vote Topic: #{@pointing_session.topic || 'None'}" %>


<%= render "votes/form" %>

app/views/pointing_sessions/_edit_form.html.erb
  <%= form_with model: @pointing_session, local: false do |form| %>
    <%= form.search_field(:topic, class: 'create_input') %>
    <%= form.submit("Set Topic") %>
  <% end %>
  

app/views/pointing_sessions/_new_form.html.erb
<%= form_with model: @pointing_session do |form| %>
  <%= form.search_field(:name, class: 'create_input') %>
  <%= form.submit("Initiate") %>
<% end %>

app/views/pointing_sessions/_pointing_session.html.erb
<div class="row">
  <div class="cell">
    <%= link_to pointing_session.name, pointing_session_path(pointing_session) %>
  </div>
</div>

app/views/pointing_sessions/index.html.erb
<h1>Welcome to Pointsetta!</h2>

<%= render partial: "new_form" %>

app/views/pointing_sessions/show.html.erb
<%= link_to "Pointsetta Root", "/" %>

<%= turbo_stream_from(@pointing_session) %>

<div class="pointing-session-name">
  <span class="title">Session: <%= @pointing_session.name %></span>
  <div class="copy-button" data-controller="clipboard" data-clipboard-text-value="<%= pointing_session_url(@pointing_session) %>">
    <button data-action="click->clipboard#copy">Copy URL</button>
  </div>
</div>

<div id="<%= dom_id(@pointing_session) %>">
  <h3> <%= "Topic: #{@pointing_session.topic || 'None'} " %> </h3>
</div>

<%= render partial: "pointing_sessions/edit_form" if @participant.administrator %>
<%= render partial: 'participants/list', locals: { pointing_session: @pointing_session } %>
<%= render partial: 'participants/vote_form', locals: { participant: @participant, pointing_session: @pointing_session } %>